# This is a basic workflow to help you get started with Actions test

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in paralleld
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
       
      - name: Run tests
        uses: matlab-actions/run-tests@v2
        with:
            test-results-pdf: test-results/pdf-results.pdf
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v4
        with:
           name: diffreports
           path: ${{ test-results}}\*.pdf
